version: '3.8'
services:
  server:
    container_name: "controlhome-api"
    image: gbaranski19/control-home-api
    env_file: ./.env
    ports:
      - 6436:6436
    restart: 'unless-stopped'
    volumes:
      - ./src/firebaseConfig.json:/server/src/firebaseConfig.json

