version: '3.8'
services:
  server:
    tty: true
    container_name: "controlhome-server"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    restart: 'unless-stopped'
    volumes:
      - ./server/src/config/firebaseConfig.json:/app/src/firebaseConfig.json

