version: "3.8"
services:
  # Vendor services
  nginx:
    tty: true
    container_name: "nginx"
    build:
      context: ./build/nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    restart: "unless-stopped"
    volumes:
      - ./deployment/certs/fullchain.pem:/etc/dockercerts/fullchain.pem
      - ./deployment/certs/privkey.pem:/etc/dockercerts/privkey.pem
    networks:
      - backend

  postgres:
    image: postgres
    container_name: "postgres"
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  emqx:
    tty: true
    image: "emqx/emqx"
    container_name: "emqx"
    restart: "unless-stopped"
    environment:
      - EMQX_NAME=emqx
      - EMQX_LOG__LEVEL=info
      - EMQX_ALLOW_ANONYMOUS=true

      - EMQX_LOADED_PLUGINS=
    ports:
      - 1883:1883 # MQTT
      - 8083:8083 # MQTT/WS
      - 18083:18083 # Dashboard
    volumes:
      - ./build/emqx/plugins:/opt/emqx/etc/plugins
    networks:
      - backend

  # My services

  emqx_auth:
    # tty: true
    container_name: "emqx_auth"
    restart: "unless-stopped"
    env_file:
      - .env
    build:
      dockerfile: ./cmd/emqx/auth/Dockerfile
      context: .
    networks:
      - backend

  auth:
    tty: true
    container_name: "auth"
    restart: "unless-stopped"
    depends_on:
      - postgres
    build:
      dockerfile: ./cmd/auth/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./web/templates:/templates
    networks:
      - backend

  fulfillment:
    tty: true
    container_name: "fulfillment"
    restart: "unless-stopped"
    depends_on:
      - postgres
    build:
      dockerfile: ./cmd/fulfillment/Dockerfile
      context: .
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
