name: 'CI'

on: [push, pull_request, workflow_dispatch]

jobs:
  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...

  lint_staticcheck:
    name: Run staticcheck linter
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install staticcheck
        run: go get honnef.co/go/tools/cmd/staticcheck

      - name: Run staticcheck
        run: staticcheck ./...
