# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auth_test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: './auth'
        run: npm install
      - name: Test
        working-directory: './auth'
        run: npm test
  device_api_test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: './device_api'
        run: npm install
      - name: Run tests
        working-directory: './device_api'
        run: npm test
