name: Deploy to Google App Engine

on:
  release:
  workflow_dispatch:


jobs:
  deploy-app-engine:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: Deploy
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
    
